### ISSUE TITLE
Support for S3 ServerSideEncryption

### ISSUE THREAD

**Issue by fmechant** [viant/afsc#1]
There is support for a custom key using `option.AES256Key`, but not for simple service side encryption with the default key.

Guess it is so simple as to implement a new option, and update `upload.go` to also set
`input.ServerSideEncryption = aws.String("AES256")`.

Will try this out in Fork. If you are interested, I could create a pull request after?

**Comment by adranwit** [comment]
Please go ahead,

**Comment by adranwit** [comment]
Let me set timebox 2 weeks from now to close this issue,

**Comment by adranwit** [comment]
Added ServerSideEncryption support on S3
