### ISSUE TITLE
s3_test imports afsc/gs

### ISSUE THREAD

**Issue by RJKeevil** [viant/afsc#6]
Hi, I was having a dig into why my app has some google cloud indirect dependencies, and i see the following with a go mod why:
github.com/viant/afsc/s3
github.com/viant/afsc/s3.test
github.com/viant/afsc/gs

I think the import of gs.NewStorager in this test is accidental. I can send a PR, just wanted to check the fix is correct:  I'd need to export s3.NewStorager (s3.newStorager -> s3.NewStorager), and replace gs.NewStorager with s3.NewStorager?

Thanks for this library, it is working great!

**Comment by RJKeevil** [comment]
Hello again @adranwit , small request, would it be possible to tag this release? We use afs in our open source project (https://github.com/knights-analytics/hugot), and am unsure what will happen when users upgrade to the latest release, will it get the previous afsc dependency?

**Comment by adranwit** [comment]
sure,
